name: Create Release on Merge to Master

on  :
    push:
        branches:
            - master

jobs:
    build     :
        if     : "!contains(github.event.head_commit.message, 'chore: update changelog')"
        name   : Build The Project
        runs-on: ubuntu-latest

        steps  :
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Set up NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 22
                    cache       : 'yarn'

            -   name: Install dependencies
                run : yarn install --frozen-lockfile

            -   name: Run build
                run : yarn build

            -   name : Create ZIP archive
                run  : |
                    cd dist
                    zip -r ../frontend-build.zip .
                shell: bash

            -   name: Upload build artifact
                uses: actions/upload-artifact@v4
                with:
                    name: frontend-build
                    path: frontend-build.zip

    versioning:
        name   : Determine Version
        runs-on: ubuntu-latest
        outputs:
            new_version: ${{ steps.tag.outputs.new_tag }}
        needs  : build

        steps  :
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Generate New Tag
                id  : tag
                uses: anothrNick/github-tag-action@1.71.0
                env :
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    DEFAULT_BUMP: patch

    changelog :
        name       : Generate Changelog
        runs-on    : ubuntu-latest
        needs      : versioning
        permissions:
            contents: write

        steps      :
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install git-chglog
                run : |
                    curl -sSL https://github.com/git-chglog/git-chglog/releases/download/v0.15.0/git-chglog_0.15.0_linux_amd64.tar.gz | tar -xz
                    sudo mv git-chglog /usr/local/bin/

            -   name: Generate Changelog
                run : git-chglog -o CHANGELOG.md


            -   name: Push The Changelog for Tag
                env :
                    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    REPO: ${{ github.repository }}
                run : |
                    LATEST_SHA=$(gh api repos/$REPO/git/ref/heads/master --jq '.object.sha')
                    FILE_SHA=$(gh api repos/$REPO/contents/CHANGELOG.md --jq '.sha' || echo "")
                    COMMIT_MESSAGE="chore: update changelog for new release"
                    gh api repos/$REPO/contents/CHANGELOG.md \
                    -X PUT \
                    -F message="$COMMIT_MESSAGE" \
                    -F content="$(base64 -w 0 CHANGELOG.md)" \
                    -F sha="$FILE_SHA" \
                    -F branch="master"

            -   name: Upload Changelog
                uses: actions/upload-artifact@v4
                with:
                    name: changelog
                    path: CHANGELOG.md

    publish   :
        name   : Publish Release
        runs-on: ubuntu-latest
        needs  : [ versioning, changelog ]

        steps  :
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Download build artifact
                uses: actions/download-artifact@v4
                with:
                    name: frontend-build

            -   name: Publish GitHub Release
                uses: softprops/action-gh-release@v2
                with:
                    tag_name   : "${{ needs.versioning.outputs.new_version }}"
                    name       : Release ${{ env.VERSION }}
                    body_path  : CHANGELOG.md
                    files      : frontend-build.zip
                    make_latest: true
                env :
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
